# Generated by Django 2.1.2 on 2018-10-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20181013_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='location',
            field=models.CharField(default='STL', max_length=255),
            preserve_default=False,
        ),
    ]
