# Generated by Django 2.1.2 on 2018-10-14 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_community_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immigrantprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='immigrantprofile',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
